"""Added users table

Revision ID: 1f628697d5f6
Revises: 
Create Date: 2022-12-20 23:01:04.947141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f628697d5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegramusers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('active', 'blocked', name='usertype'), nullable=True),
    sa.Column('raiting', sa.Float(precision=1), nullable=True, default=0),
    sa.Column('likes_amount', sa.Integer(), nullable=True, default=0),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegramusers_id'), 'telegramusers', ['id'], unique=False)
    op.create_index(op.f('ix_telegramusers_telegram_id'), 'telegramusers', ['telegram_id'], unique=True)
    op.create_table('telegramuserstokens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['telegramusers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_telegramuserstokens_id'), 'telegramuserstokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegramuserstokens_id'), table_name='telegramuserstokens')
    op.drop_table('telegramuserstokens')
    op.drop_index(op.f('ix_telegramusers_telegram_id'), table_name='telegramusers')
    op.drop_index(op.f('ix_telegramusers_id'), table_name='telegramusers')
    op.drop_table('telegramusers')
    # ### end Alembic commands ###
