"""added third tag

Revision ID: 3b6300a2dac9
Revises: dbcd2493dc6a
Create Date: 2023-01-17 01:00:10.823208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6300a2dac9'
down_revision = 'dbcd2493dc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('third_tag', sa.Enum('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'), nullable=False))
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('cards', 'third_tag')
    # ### end Alembic commands ###
