"""alter maximum length to bio field

Revision ID: 46816119701f
Revises: 78b7206df770
Create Date: 2023-01-19 03:15:02.606407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46816119701f'
down_revision = '78b7206df770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'bio',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('cards', 'bio',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
