"""created initial tables

Revision ID: 492f9556bfac
Revises: 
Create Date: 2022-12-23 20:41:18.812924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492f9556bfac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegramusers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegraph_access_token', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('active', 'blocked', name='usertype'), nullable=True),
    sa.Column('role', sa.Enum('user', 'moderator', name='userrole'), nullable=True),
    sa.Column('raiting', sa.Float(precision=1), nullable=True),
    sa.Column('likes_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegramusers_id'), 'telegramusers', ['id'], unique=False)
    op.create_index(op.f('ix_telegramusers_telegram_id'), 'telegramusers', ['telegram_id'], unique=True)
    op.create_table('posts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('telegraph_url', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('not_published', 'not_accepted', 'published', name='poststatus'), nullable=True),
    sa.Column('views_amount', sa.Integer(), nullable=True),
    sa.Column('likes_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['telegramusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_telegramusers_telegram_id'), table_name='telegramusers')
    op.drop_index(op.f('ix_telegramusers_id'), table_name='telegramusers')
    op.drop_table('telegramusers')
    # ### end Alembic commands ###
