"""added like system

Revision ID: 667fc1c8da16
Revises: 6d58b9d60595
Create Date: 2023-01-04 22:34:41.994257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '667fc1c8da16'
down_revision = '6d58b9d60595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('like_author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('liked', 'unliked', name='likestatus'), nullable=True),
    sa.ForeignKeyConstraint(['like_author'], ['telegramusers.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.drop_column('posts', 'likes_amount')
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('posts', sa.Column('likes_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
