"""fixed_views_amount_added_not_approves status

Revision ID: 6d58b9d60595
Revises: 987426a82a6c
Create Date: 2022-12-30 19:45:33.685745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d58b9d60595'
down_revision = '987426a82a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views_amount')
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('posts', sa.Column('views_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
