"""added raiting to posts

Revision ID: 911853340766
Revises: 6aab14a28946
Create Date: 2023-01-27 14:46:08.994313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911853340766'
down_revision = '6aab14a28946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('raiting', sa.Integer(), nullable=True))
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('posts', 'raiting')
    # ### end Alembic commands ###
