"""created follow system

Revision ID: 9400900c5086
Revises: 2024eba7370d
Create Date: 2022-12-27 01:59:44.259229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9400900c5086'
down_revision = '2024eba7370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FollowRelationship',
    sa.Column('FollowerID', postgresql.UUID(), nullable=True),
    sa.Column('FollowingID', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['FollowerID'], ['telegramusers.id'], ),
    sa.ForeignKeyConstraint(['FollowingID'], ['telegramusers.id'], )
    )
    op.add_column('posts', sa.Column('subtitle', sa.String(length=300), nullable=True))
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('posts', 'subtitle')
    op.drop_table('FollowRelationship')
    # ### end Alembic commands ###
