"""added name and surname

Revision ID: 959ac0e3954e
Revises: 8c87ecc172b6
Create Date: 2023-01-13 18:25:06.914624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959ac0e3954e'
down_revision = '8c87ecc172b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramusers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('telegramusers', sa.Column('surname', sa.String(), nullable=True))
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('telegramusers', 'surname')
    op.drop_column('telegramusers', 'first_name')
    # ### end Alembic commands ###
