"""fixing follow system

Revision ID: 987426a82a6c
Revises: cf9f865b5443
Create Date: 2022-12-27 14:24:26.760620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '987426a82a6c'
down_revision = 'cf9f865b5443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_relationship',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('FollowerID', postgresql.UUID(), nullable=False),
    sa.Column('FollowingID', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['FollowerID'], ['telegramusers.id'], ),
    sa.ForeignKeyConstraint(['FollowingID'], ['telegramusers.id'], ),
    sa.PrimaryKeyConstraint('id', 'FollowerID', 'FollowingID')
    )
    op.create_index(op.f('ix_follow_relationship_id'), 'follow_relationship', ['id'], unique=False)
    op.drop_table('FollowRelationship')
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('FollowRelationship',
    sa.Column('FollowerID', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('FollowingID', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['FollowerID'], ['telegramusers.id'], name='FollowRelationship_FollowerID_fkey'),
    sa.ForeignKeyConstraint(['FollowingID'], ['telegramusers.id'], name='FollowRelationship_FollowingID_fkey')
    )
    op.drop_index(op.f('ix_follow_relationship_id'), table_name='follow_relationship')
    op.drop_table('follow_relationship')
    # ### end Alembic commands ###
