"""added nullable=true to tags

Revision ID: a9f223e73926
Revises: 46816119701f
Create Date: 2023-01-20 13:16:46.151555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f223e73926'
down_revision = '46816119701f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'first_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=True)
    op.alter_column('cards', 'second_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=True)
    op.alter_column('cards', 'third_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=True)
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('cards', 'third_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=False)
    op.alter_column('cards', 'second_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=False)
    op.alter_column('cards', 'first_tag',
               existing_type=postgresql.ENUM('fintech', 'design', 'adobe', 'figma', 'tilda', 'java', 'script', 'python', 'ci_plus_plus', 'php', 'google_analytics', 'yandex_metrics', 'time_menegment', 'conversation', 'leadership', 'mentoring', 'tracking', 'higher_school_of_economics', 'pleska', 'mgu', 'mfti', 'mifi', 'rudn', 'mgimo', 'ranhigs', 'spgu', 'spgtu', 'ngu', 'nngu', 'tpu', 'project_manager', 'product_manager', 'startup', 'data_science', 'smm', 'developer', 'analytic', 'engineer', 'ux_ui', name='tag'),
               nullable=False)
    # ### end Alembic commands ###
