"""added primary key to follow system

Revision ID: cf9f865b5443
Revises: 9400900c5086
Create Date: 2022-12-27 14:09:35.528455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9f865b5443'
down_revision = '9400900c5086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FollowRelationship', 'FollowerID',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('FollowRelationship', 'FollowingID',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegramusers', 'raiting',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('FollowRelationship', 'FollowingID',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('FollowRelationship', 'FollowerID',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
